name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    timeout-minutes: 360
    

    runs-on: windows-latest

    steps:
    - name: Download
      run: |
          Invoke-WebRequest https://swupdate.openvpn.org/community/releases/OpenVPN-2.6.10-I001-amd64.msi -OutFile openvpn.msi
          $file = "openvpn.msi" 
          $log = "install.log" 
          $procMain = Start-Process "msiexec" "/i `"$file`" /qn /l*! `"$log`"" -NoNewWindow -PassThru
          $procLog = Start-Process "powershell" "Get-Content -Path `"$log`" -Wait" -NoNewWindow -PassThru 
          $procMain.WaitForExit() 
          $procLog.Kill()
      
    - name: Auth
    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
    - name: Create Tunnel
      run: | 
           set PATH=%PATH%;C:\Program Files\OpenVPN\bin\
           openvpn --config tarekmj.DL.ovpn
          
